version: '3.8'

services:
  app:
    container_name: whatsapp-messaging-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
    depends_on:
      - mongodb
    networks:
      - internal_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - internal_network

volumes:
  mongodb_data:

networks:
  internal_network:
    external: true
