version: '3'
services:
  mongodb:
    image: mongo
    container_name: database
    ports:
      - ${MONGODB_PORT}:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongodb_data:
