version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    networks:
      - nginx_network
      - internal_network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    networks:
      - internal_network
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    networks:
      - internal_network
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    # Removido o mapeamento da porta do Kibana, pois o acesso será feito via Nginx Proxy Manager.
    # Não precisa expor a porta 5601 diretamente.
    restart: always

networks:
  nginx_network:
    driver: bridge
  internal_network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
