version: '3'

services:
  mongodb:
    image: mongo
    container_name: database
    ports:
      - ${MONGODB_PORT}:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    container_name: eventstore
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
    ports:
      - 2113:2113  # HTTP (dashboard e API REST)
      - 1113:1113  # TCP gRPC
    volumes:
      - esdata:/var/lib/eventstore
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    env_file: .env
    command: >
      redis-server
      --port ${REDIS_PORT}
      --requirepass ${REDIS_PASSWORD}
      --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} allcommands allkeys
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540  # Porta padrão do RedisInsight
    restart: unless-stopped

volumes:
  mongodb_data:
  esdata:
  redis_data:
